# Файл для разработки, автоматически подключается при выполнении docker-compose up
services:
  nginx:
    ports:
      - "${HOST_FRONTEND_PORT_DEV}:80"

  frontend:
    volumes:
      - ./frontend:/var/www/frontend

  backend:
    volumes:
      - ./backend:/var/www/backend
    ports:
      - "${HOST_BACKEND_PORT_DEV}:9000"
    environment:
      APP_DEBUG: "true"
      PHP_IDE_CONFIG: "serverName=docker"
      XDEBUG_MODE: "develop,debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"

  db:
    ports:
      - "${HOST_DB_PORT_DEV}:5432"
