import { definePreset } from '@primevue/themes'
import Aura from '@primevue/themes/aura'

const Preset = definePreset(Aura, {
  primitive: {
    borderRadius: {
      none: '0',
      xs: '2px',
      sm: '4px',
      md: '6px',
      lg: '10px',
      xl: '14px',
    },
    emerald: {
      50: '#ecfdf5',
      100: '#d1fae5',
      200: '#a7f3d0',
      300: '#6ee7b7',
      400: '#34d399',
      500: '#10b981',
      600: '#059669',
      700: '#047857',
      800: '#065f46',
      900: '#064e3b',
      950: '#022c22',
    },
    green: {
      50: '#f0fdf4',
      100: '#dcfce7',
      200: '#bbf7d0',
      300: '#86efac',
      400: '#4ade80',
      500: '#22c55e',
      600: '#16a34a',
      700: '#15803d',
      800: '#166534',
      900: '#14532d',
      950: '#052e16',
    },
    lime: {
      50: '#f7fee7',
      100: '#ecfccb',
      200: '#d9f99d',
      300: '#bef264',
      400: '#a3e635',
      500: '#84cc16',
      600: '#65a30d',
      700: '#4d7c0f',
      800: '#3f6212',
      900: '#365314',
      950: '#1a2e05',
    },
    red: {
      50: '#fef2f2',
      100: '#fee2e2',
      200: '#fecaca',
      300: '#fca5a5',
      400: '#f87171',
      500: '#ef4444',
      600: '#dc2626',
      700: '#b91c1c',
      800: '#991b1b',
      900: '#7f1d1d',
      950: '#450a0a',
    },
    orange: {
      50: '#fff7ed',
      100: '#ffedd5',
      200: '#fed7aa',
      300: '#fdba74',
      400: '#fb923c',
      500: '#f97316',
      600: '#ea580c',
      700: '#c2410c',
      800: '#9a3412',
      900: '#7c2d12',
      950: '#431407',
    },
    amber: {
      50: '#fffbeb',
      100: '#fef3c7',
      200: '#fde68a',
      300: '#fcd34d',
      400: '#fbbf24',
      500: '#f59e0b',
      600: '#d97706',
      700: '#b45309',
      800: '#92400e',
      900: '#78350f',
      950: '#451a03',
    },
    yellow: {
      50: '#fefce8',
      100: '#fef9c3',
      200: '#fef08a',
      300: '#fde047',
      400: '#facc15',
      500: '#eab308',
      600: '#ca8a04',
      700: '#a16207',
      800: '#854d0e',
      900: '#713f12',
      950: '#422006',
    },
    teal: {
      50: '#f0fdfa',
      100: '#ccfbf1',
      200: '#99f6e4',
      300: '#5eead4',
      400: '#2dd4bf',
      500: '#14b8a6',
      600: '#0d9488',
      700: '#0f766e',
      800: '#115e59',
      900: '#134e4a',
      950: '#042f2e',
    },
    cyan: {
      50: '#ecfeff',
      100: '#cffafe',
      200: '#a5f3fc',
      300: '#67e8f9',
      400: '#22d3ee',
      500: '#06b6d4',
      600: '#0891b2',
      700: '#0e7490',
      800: '#155e75',
      900: '#164e63',
      950: '#083344',
    },
    sky: {
      50: '#f3fbfe',
      100: '#c5e9fa',
      200: '#97d8f6',
      300: '#6ac7f1',
      400: '#3cb6ed',
      500: '#0ea5e9',
      600: '#0c8cc6',
      700: '#0a73a3',
      800: '#085b80',
      900: '#06425d',
      950: '#04293a',
    },
    blue: {
      50: '#eff6ff',
      100: '#dbeafe',
      200: '#bfdbfe',
      300: '#93c5fd',
      400: '#60a5fa',
      500: '#3b82f6',
      600: '#2563eb',
      700: '#1d4ed8',
      800: '#1e40af',
      900: '#1e3a8a',
      950: '#172554',
    },
    indigo: {
      50: '#eef2ff',
      100: '#e0e7ff',
      200: '#c7d2fe',
      300: '#a5b4fc',
      400: '#818cf8',
      500: '#6366f1',
      600: '#4f46e5',
      700: '#4338ca',
      800: '#3730a3',
      900: '#312e81',
      950: '#1e1b4b',
    },
    violet: {
      50: '#f5f3ff',
      100: '#ede9fe',
      200: '#ddd6fe',
      300: '#c4b5fd',
      400: '#a78bfa',
      500: '#8b5cf6',
      600: '#7c3aed',
      700: '#6d28d9',
      800: '#5b21b6',
      900: '#4c1d95',
      950: '#2e1065',
    },
    purple: {
      50: '#faf5ff',
      100: '#f3e8ff',
      200: '#e9d5ff',
      300: '#d8b4fe',
      400: '#c084fc',
      500: '#a855f7',
      600: '#9333ea',
      700: '#7e22ce',
      800: '#6b21a8',
      900: '#581c87',
      950: '#3b0764',
    },
    fuchsia: {
      50: '#fdf4ff',
      100: '#fae8ff',
      200: '#f5d0fe',
      300: '#f0abfc',
      400: '#e879f9',
      500: '#d946ef',
      600: '#c026d3',
      700: '#a21caf',
      800: '#86198f',
      900: '#701a75',
      950: '#4a044e',
    },
    pink: {
      50: '#fdf2f8',
      100: '#fce7f3',
      200: '#fbcfe8',
      300: '#f9a8d4',
      400: '#f472b6',
      500: '#ec4899',
      600: '#db2777',
      700: '#be185d',
      800: '#9d174d',
      900: '#831843',
      950: '#500724',
    },
    rose: {
      50: '#fff1f2',
      100: '#ffe4e6',
      200: '#fecdd3',
      300: '#fda4af',
      400: '#fb7185',
      500: '#f43f5e',
      600: '#e11d48',
      700: '#be123c',
      800: '#9f1239',
      900: '#881337',
      950: '#4c0519',
    },
    slate: {
      50: '#f7f8f9',
      100: '#e2e6ec',
      200: '#bcc3cd',
      300: '#9fa9b7',
      400: '#818ea1',
      500: '#64748b',
      600: '#556376',
      700: '#465161',
      800: '#37404c',
      900: '#282e38',
      950: '#191d23',
    },
    gray: {
      50: '#f9fafb',
      100: '#f3f4f6',
      200: '#e5e7eb',
      300: '#d1d5db',
      400: '#9ca3af',
      500: '#6b7280',
      600: '#4b5563',
      700: '#374151',
      800: '#1f2937',
      900: '#111827',
      950: '#030712',
    },
    zinc: {
      50: '#fafafb',
      100: '#e7e9e9',
      200: '#d5d8d8',
      300: '#c2c7c7',
      400: '#b0b5b6',
      500: '#9da4a5',
      600: '#858b8c',
      700: '#6e7373',
      800: '#565a5b',
      900: '#3f4242',
      950: '#272929',
    },
    neutral: {
      50: '#fafafa',
      100: '#f5f5f5',
      200: '#e5e5e5',
      300: '#d4d4d4',
      400: '#a3a3a3',
      500: '#737373',
      600: '#525252',
      700: '#404040',
      800: '#262626',
      900: '#171717',
      950: '#0a0a0a',
    },
    stone: {
      50: '#fafaf9',
      100: '#f5f5f4',
      200: '#e7e5e4',
      300: '#d6d3d1',
      400: '#a8a29e',
      500: '#78716c',
      600: '#57534e',
      700: '#44403c',
      800: '#292524',
      900: '#1c1917',
      950: '#0c0a09',
    },
  },
  semantic: {
    transitionDuration: '0.2s',
    focusRing: {
      width: '1px',
      style: 'solid',
      color: '{primary.color}',
      offset: '2px',
      shadow: 'none',
    },
    disabledOpacity: '1',
    iconSize: '2rem',
    anchorGutter: '2px',
    primary: {
      50: '#f9f9fe',
      100: '#e1e1fb',
      200: '#cac8f7',
      300: '#b2b0f4',
      400: '#9b98f0',
      500: '#8380ed',
      600: '#6f6dc9',
      700: '#5c5aa6',
      800: '#484682',
      900: '#34335f',
      950: '#21203b',
    },
    formField: {
      paddingX: '0.75rem',
      paddingY: '0.75rem',
      sm: {
        fontSize: '1.2rem',
        paddingX: '0.625rem',
        paddingY: '0.625rem',
      },
      lg: {
        fontSize: '1.6rem',
        paddingX: '0.875rem',
        paddingY: '0.875rem',
      },
      borderRadius: '{border.radius.lg}',
      focusRing: {
        width: '0',
        style: 'none',
        color: 'transparent',
        offset: '0',
        shadow: 'none',
      },
      transitionDuration: '{transition.duration}',
    },
    list: {
      padding: '0.25rem 0.25rem',
      gap: '0.2rem',
      header: {
        padding: '0.5rem 1rem 0.25rem 1rem',
      },
      option: {
        padding: '1rem 1rem',
        borderRadius: '{border.radius.md}',
      },
      optionGroup: {
        padding: '0.5rem 0.75rem',
        fontWeight: '600',
      },
    },
    content: {
      borderRadius: '{border.radius.lg}',
    },
    mask: {
      transitionDuration: '0.15s',
    },
    navigation: {
      list: {
        padding: '0.25rem 0.25rem',
        gap: '0',
      },
      item: {
        padding: '0.5rem 0.75rem',
        borderRadius: '{border.radius.md}',
        gap: '0.5rem',
      },
      submenuLabel: {
        padding: '0.5rem 0.75rem',
        fontWeight: '600',
      },
      submenuIcon: {
        size: '0.875rem',
      },
    },
    overlay: {
      select: {
        borderRadius: '{border.radius.lg}',
        shadow:
          '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
      },
      popover: {
        borderRadius: '{border.radius.lg}',
        padding: '1rem',
        shadow:
          '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
      },
      modal: {
        borderRadius: '{border.radius.lg}',
        padding: '1rem',
        shadow:
          '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
      },
      navigation: {
        shadow:
          '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)',
      },
    },
    colorScheme: {
      light: {
        surface: {
          0: '#ffffff',
          50: '#f8f7fa',
          100: '#e3deec',
          200: '#c2bad0',
          300: '#a79cbb',
          400: '#8c7da7',
          500: '#715f92',
          600: '#60517c',
          700: '#4f4366',
          800: '#3e3450',
          900: '#2d263a',
          950: '#1c1825',
        },
        primary: {
          color: '{primary.500}',
          contrastColor: '#ffffff',
          hoverColor: '{primary.600}',
          activeColor: '{primary.600}',
        },
        highlight: {
          background: '{surface.100}',
          focusBackground: '{surface.100}',
          color: '{surface.700}',
          focusColor: '{surface.800}',
        },
        mask: {
          background: 'rgba(0,0,0,0.4)',
          color: '{surface.200}',
        },
        formField: {
          background: '{surface.0}',
          disabledBackground: '{surface.0}',
          filledBackground: '{surface.100}',
          filledHoverBackground: '{surface.100}',
          filledFocusBackground: '{surface.100}',
          borderColor: '{surface.200}',
          hoverBorderColor: '{primary.color}',
          focusBorderColor: '{primary.color}',
          invalidBorderColor: '{red.400}',
          color: '{primary.950}',
          disabledColor: '{surface.200}',
          placeholderColor: '{surface.500}',
          invalidPlaceholderColor: '{red.500}',
          floatLabelColor: '{surface.500}',
          floatLabelFocusColor: '{primary.600}',
          floatLabelActiveColor: '{surface.500}',
          floatLabelInvalidColor: '{form.field.invalid.placeholder.color}',
          iconColor: '{primary.color}',
          shadow: '0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)',
        },
        text: {
          color: '{primary.950}',
          hoverColor: '{primary.950}',
          mutedColor: '{primary.600}',
          hoverMutedColor: '{primary.700}',
        },
        content: {
          background: '{surface.0}',
          hoverBackground: '{surface.100}',
          borderColor: '{surface.200}',
          color: '{text.color}',
          hoverColor: '{text.hover.color}',
        },
        overlay: {
          select: {
            background: '{surface.0}',
            borderColor: '{surface.200}',
            color: '{text.color}',
          },
          popover: {
            background: '{surface.0}',
            borderColor: '{surface.200}',
            color: '{text.color}',
          },
          modal: {
            background: '{surface.0}',
            borderColor: '{surface.200}',
            color: '{text.color}',
          },
        },
        list: {
          option: {
            focusBackground: '{surface.100}',
            selectedBackground: '{highlight.background}',
            selectedFocusBackground: '{highlight.focus.background}',
            color: '{text.color}',
            focusColor: '{text.hover.color}',
            selectedColor: '{highlight.color}',
            selectedFocusColor: '{highlight.focus.color}',
            icon: {
              color: '{surface.400}',
              focusColor: '{surface.500}',
            },
          },
          optionGroup: {
            background: 'transparent',
            color: '{text.muted.color}',
          },
        },
        navigation: {
          item: {
            focusBackground: '{surface.100}',
            activeBackground: '{surface.100}',
            color: '{text.color}',
            focusColor: '{text.hover.color}',
            activeColor: '{text.hover.color}',
            icon: {
              color: '{surface.400}',
              focusColor: '{surface.500}',
              activeColor: '{surface.500}',
            },
          },
          submenuLabel: {
            background: 'transparent',
            color: '{text.muted.color}',
          },
          submenuIcon: {
            color: '{surface.400}',
            focusColor: '{surface.500}',
            activeColor: '{surface.500}',
          },
        },
      },
      dark: {
        surface: {
          0: '#ffffff',
          50: '#fafafa',
          100: '#f4f4f5',
          200: '#e4e4e7',
          300: '#d4d4d8',
          400: '#a1a1aa',
          500: '#71717a',
          600: '#52525b',
          700: '#3f3f46',
          800: '#27272a',
          900: '#18181b',
          950: '#09090b',
        },
        primary: {
          color: '{primary.400}',
          contrastColor: '{surface.900}',
          hoverColor: '{primary.300}',
          activeColor: '{primary.200}',
        },
        highlight: {
          background: 'color-mix(in srgb, {primary.400}, transparent 84%)',
          focusBackground: 'color-mix(in srgb, {primary.400}, transparent 76%)',
          color: 'rgba(255,255,255,.87)',
          focusColor: 'rgba(255,255,255,.87)',
        },
        mask: {
          background: 'rgba(0,0,0,0.6)',
          color: '{surface.200}',
        },
        formField: {
          background: '{surface.950}',
          disabledBackground: '{surface.700}',
          filledBackground: '{surface.800}',
          filledHoverBackground: '{surface.800}',
          filledFocusBackground: '{surface.800}',
          borderColor: '{surface.600}',
          hoverBorderColor: '{surface.500}',
          focusBorderColor: '{primary.color}',
          invalidBorderColor: '{red.300}',
          color: '{surface.0}',
          disabledColor: '{surface.400}',
          placeholderColor: '{surface.400}',
          invalidPlaceholderColor: '{red.400}',
          floatLabelColor: '{surface.400}',
          floatLabelFocusColor: '{primary.color}',
          floatLabelActiveColor: '{surface.400}',
          floatLabelInvalidColor: '{form.field.invalid.placeholder.color}',
          iconColor: '{surface.400}',
          shadow: '0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)',
        },
        text: {
          color: '{surface.0}',
          hoverColor: '{surface.0}',
          mutedColor: '{surface.400}',
          hoverMutedColor: '{surface.300}',
        },
        content: {
          background: '{surface.900}',
          hoverBackground: '{surface.800}',
          borderColor: '{surface.700}',
          color: '{text.color}',
          hoverColor: '{text.hover.color}',
        },
        overlay: {
          select: {
            background: '{surface.900}',
            borderColor: '{surface.700}',
            color: '{text.color}',
          },
          popover: {
            background: '{surface.900}',
            borderColor: '{surface.700}',
            color: '{text.color}',
          },
          modal: {
            background: '{surface.900}',
            borderColor: '{surface.700}',
            color: '{text.color}',
          },
        },
        list: {
          option: {
            focusBackground: '{surface.800}',
            selectedBackground: '{highlight.background}',
            selectedFocusBackground: '{highlight.focus.background}',
            color: '{text.color}',
            focusColor: '{text.hover.color}',
            selectedColor: '{highlight.color}',
            selectedFocusColor: '{highlight.focus.color}',
            icon: {
              color: '{surface.500}',
              focusColor: '{surface.400}',
            },
          },
          optionGroup: {
            background: 'transparent',
            color: '{text.muted.color}',
          },
        },
        navigation: {
          item: {
            focusBackground: '{surface.800}',
            activeBackground: '{surface.800}',
            color: '{text.color}',
            focusColor: '{text.hover.color}',
            activeColor: '{text.hover.color}',
            icon: {
              color: '{surface.500}',
              focusColor: '{surface.400}',
              activeColor: '{surface.400}',
            },
          },
          submenuLabel: {
            background: 'transparent',
            color: '{text.muted.color}',
          },
          submenuIcon: {
            color: '{surface.500}',
            focusColor: '{surface.400}',
            activeColor: '{surface.400}',
          },
        },
      },
    },
  },
  components: {
    button: {
      colorScheme: {
        light: {
          primary: {
            color: '{primary.contrast.color}',
            borderColor: '{primary.500}',
            background: '{primary.500}',
            hoverColor: '{primary.contrast.color}',
            hoverBorderColor: '{primary.600}',
            hoverBackground: '{primary.600}',
            activeColor: '{primary.100}',
            activeBorderColor: '{primary.500}',
            activeBackground: '{primary.500}',
          },
          secondary: {
            color: '{primary.contrast.color}',
            borderColor: '{surface.400}',
            background: '{surface.400}',
            hoverColor: '{primary.contrast.color}',
            hoverBorderColor: '{surface.500}',
            hoverBackground: '{surface.500}',
            activeColor: '{surface.100}',
            activeBorderColor: '{surface.400}',
            activeBackground: '{surface.400}',
          },
          success: {
            color: '{primary.contrast.color}',
            borderColor: '{green.400}',
            background: '{green.400}',
            hoverColor: '{primary.contrast.color}',
            hoverBorderColor: '{green.500}',
            hoverBackground: '{green.500}',
            activeColor: '{green.100}',
            activeBorderColor: '{green.400}',
            activeBackground: '{green.400}',
          },
          danger: {
            color: '{primary.contrast.color}',
            borderColor: '{red.400}',
            background: '{red.400}',
            hoverColor: '{primary.contrast.color}',
            hoverBorderColor: '{red.500}',
            hoverBackground: '{red.500}',
            activeColor: '{red.100}',
            activeBorderColor: '{red.400}',
            activeBackground: '{red.400}',
          },
          outlined: {
            primary: {
              color: '{primary.500}',
              borderColor: '{primary.500}',
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
            secondary: {
              color: '{surface.400}',
              borderColor: '{surface.400}',
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
            success: {
              color: '{green.400}',
              borderColor: '{green.400}',
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
            info: {
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
            warn: {
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
            help: {
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
            danger: {
              color: '{red.400}',
              borderColor: '{red.400}',
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
          },
          text: {
            primary: {
              color: '{primary.500}',
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
            secondary: {
              color: '{surface.400}',
              hoverColor: '{surface.500}',
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
            success: {
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
            info: {
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
            warn: {
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
            help: {
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
            danger: {
              hoverBackground: 'transparent',
              activeBackground: 'transparent',
            },
          },
        },
      },
    },
    message: {
      text: {
        fontSize: 'inherit',
        smFontSize: '1.2rem',
        lgFontSize: '1.6rem',
        fontWeight: 'inherit',
      },
    },
    floatlabel: {
      activeFontSize: '1.2rem',
    },
    checkbox: {
      width: '16px',
      height: '16px',
      borderRadius: '{border.radius.sm}',
      sm: {
        width: '12px',
        height: '12px',
      },
      lg: {
        width: '20px',
        height: '20px',
      },
      icon: {
        smSize: '6px',
        size: '10px',
        lgSize: '12px',
      },
      colorScheme: {
        light: {
          borderColor: '{primary.200}',
          hoverBorderColor: '{primary.color}',
          checked: {
            background: '{surface.0}',
            hoverBackground: '{surface.0}',
            borderColor: '{primary.color}',
            hoverBorderColor: '{primary.color}',
          },
          icon: {
            color: '{primary.color}',
            checkedColor: '{primary.color}',
            checkedHoverColor: '{primary.color}',
            disabledColor: '{surface.200}',
          },
        },
      },
    },
    radiobutton: {
      width: '16px',
      height: '16px',
      sm: {
        width: '12px',
        height: '12px',
      },
      lg: {
        width: '20px',
        height: '20px',
      },
      icon: {
        smSize: '6px',
        size: '8px',
        lgSize: '10px',
      },
      colorScheme: {
        light: {
          checked: {
            background: '{surface.0}',
            hoverBackground: '{surface.0}',
          },
          icon: {
            color: '{primary.color}',
            checkedColor: '{primary.color}',
            checkedHoverColor: '{primary.color}',
            disabledColor: '{surface.200}',
          },
        },
      },
    },
    toggleswitch: {
      width: '34px',
      height: '20px',
      handle: {
        size: '14px',
      },
      colorScheme: {
        light: {
          background: '{surface.0}',
          hoverBackground: '{surface.0}',
          checkedBackground: '{surface.0}',
          checkedHoverBackground: '{surface.0}',
          borderColor: '{surface.200}',
          hoverBorderColor: '{primary.color}',
          checkedBorderColor: '{primary.color}',
          checkedHoverBorderColor: '{primary.color}',
          handle: {
            background: '{surface.200}',
            hoverBackground: '{surface.200}',
            checkedBackground: '{primary.color}',
            checkedHoverBackground: '{primary.color}',
            disabledBackground: '{surface.100}',
          },
        },
      },
    },
    multiselect: {
      chipBorderRadius: '10rem',
    },
    chip: {
      paddingX: '0.3rem',
      paddingY: '0.3rem',
      iconSize: '2rem',
      remove: {
        iconSize: '2rem',
      },
      colorScheme: {
        light: {
          iconColor: '{surface.500}',
          remove: {
            iconColor: '{surface.500}',
          },
        },
      },
    },
    toast: {
      width: '30rem',
      contentPadding: '1.5rem',
      contentGap: '1.5rem',
      summary: {
        fontWeight: '700',
        fontSize: '1.6rem',
      },
      detail: {
        fontWeight: '400',
        fontSize: 'initial',
      },
      colorScheme: {
        light: {
          success: {
            color: '{text.color}',
            background: '{surface.50}',
            borderColor: '{green.500}',
          },
          info: {
            color: '{text.color}',
            background: '{surface.50}',
            borderColor: '{sky.500}',
          },
          warn: {
            color: '{text.color}',
            background: '{surface.50}',
            borderColor: '{amber.500}',
          },
          error: {
            color: '{text.color}',
            background: '{surface.50}',
            borderColor: '{red.400}',
          },
          secondary: {
            color: '{text.color}',
            background: '{surface.50}',
            borderColor: '{gray.500}',
          },
          contrast: {
            color: '{primary.color}',
            detailColor: '{text.color}',
            background: '{surface.50}',
            borderColor: '{primary.color}',
          },
        },
      },
    },
    datepicker: {
      select: {
        monthPadding: '0.5rem 1rem',
        yearPadding: '0.5rem 1rem',
      },
      titleFontWeight: '700',
      monthViewMargin: '1rem 0',
      dayViewMargin: '1rem 0',
      weekDayFontWeight: '700',
      date: {
        width: '3rem',
        height: '3rem',
        borderRadius: '{border.radius.lg}',
      },
      colorScheme: {
        light: {
          headerColor: '{primary.color}',
          select: {
            month: {
              color: '{primary.color}',
              hoverColor: '{primary.700}',
              hoverBackground: 'transparent',
            },
            year: {
              color: '{primary.color}',
              hoverColor: '{primary.700}',
              hoverBackground: 'transparent',
            },
          },
          date: {
            hoverColor: '{primary.contrastColor}',
            hoverBackground: '{primary.color}',
            rangeSelectedColor: '{primary.contrastColor}',
            rangeSelectedBackground: '{primary.color}',
          },
          today: {
            color: '{primary.color}',
            background: 'transparent',
          },
        },
      },
    },
    divider: {
      colorScheme: {
        light: {
          contentBackground: '{surface.50}',
        },
      },
    },
    chip: {
      paddingX: '0.3rem',
      paddingY: '0.3rem',
      gap: '0',
      borderRadius: '10rem',
      colorScheme: {
        light: {
          iconColor: '{surface.500}',
          removeIconColor: '{surface.500}',
        },
      },
    },
    badge: {
      fontSize: '1.2rem',
      fontWeight: '400',
      minWidth: '1.8rem',
      height: '1.8rem',
      padding: '0.5rem 0.5rem',
      borderRadius: '10rem',
      xl: {
        fontSize: '1.6rem',
        minWidth: '2.2rem',
        height: '2.2rem',
      },
      lg: {
        fontSize: '1.4rem',
        minWidth: '2rem',
        height: '2rem',
      },
      sm: {
        fontSize: '1rem',
        minWidth: '1.6rem',
        height: '1.6rem',
      },
      dotSize: '0.6rem',
      colorScheme: {
        light: {
          primaryBackground: '{surface.500}',
        },
      },
    },
    tabs: {
      tablist: {
        border: {
          width: '0 0 3px 0',
          color: 'transparent',
        },
      },
      tab: {
        margin: '0 0 -3px 0',
        border: {
          width: '0 0 3px 0',
          color: 'transparent',
        },
        color: '{text.color}',
        hoverColor: '{primary.color}',
        hoverBorderColor: 'transparent',
      },
      active: {
        barHeight: '3px',
        barBottom: '-3px',
      },
      colorScheme: {
        light: {
          tablistBackground: '{surface.50}',
          tabpanelBackground: '{surface.50}',
          nav: {
            button: {
              color: '{primary.color}',
              hoverColor: '{primary.hover.color}',
              background: '{surface.50}',
              shadow: '0px 0px 10px 10px {surface.50}',
            },
          },
        },
      },
    },
    fileupload: {
      headerPadding: '1rem 1rem 0.5rem 1rem',
      contentPadding: '0.5rem 1rem 1rem 1rem',
    },
    // Tooltip options not working because of PrimeVue bug
    tooltip: {
      maxWidth: '30rem',
      gutter: '0.5rem',
      colorScheme: {
        light: {
          color: '{text.color}',
          background: '{surface.50}',
        },
      },
    },
    confirmpopup: {
      arrowOffset: 'calc({confirmpopupBorderRadius} * 2.5)',
    },
    dialog: {
      title: {
        fontSize: '1.6rem',
        fontWeight: '600',
      },
      footerGap: '1rem',
    },
    popover: {
      arrowOffset: 'calc({popoverBorderRadius} * 2)',
    },
    colorpicker: {
      previewWidth: '3rem',
      previewHeight: '3rem',
    },
    scrollpanel: {
      bar: {
        size: '0.6rem',
        borderRadius: '{border.radius.md}',
      },
      colorScheme: {
        light: {
          barBackground: '{primary.300}',
        },
      },
    },
    fieldset: {
      colorScheme: {
        light: {
          legend: {
            background: 'transparent',
            hoverBackground: 'transparent',
          },
        },
      },
    },
    card: {
      title: {
        fontSize: '1.6rem',
        fontWeight: '600',
      },
      bodyGap: '1rem',
      colorScheme: {
        light: {
          subtitleColor: '{surface.300}',
        },
      },
    },
    paginator: {
      colorScheme: {
        light: {
          background: 'transparent',
        },
      },
    },
    progressspinner: {
      colorScheme: {
        light: {
          root: {
            'color.1': '{primary.color}',
            'color.2': '{primary.color}',
            'color.3': '{primary.color}',
            'color.4': '{primary.color}',
          },
        },
      },
    },
  },
})

export default Preset
